### PR TITLE
feat(info.jl): added get_fps

### PR DESCRIPTION
**Pull request by AbelHo**
function to retrieve video fps

### CODE REVIEW

**Comment by IanButterworth** [comment]
`VideoIO.framerate(f)` exists, but I notice it is only mentioned in passing in the manual. 

Does that meet your needs? If so can you PR to add that to the manual. 

Thanks!

**Comment by AbelHo** [comment]
Thanks for your quick response!
`VideoIO.framerate(f)` gives 1//0 for the videos I have. I hope I am not doing something wrong?

**Comment by IanButterworth** [comment]
I think it requires that at least one frame has been read. Can you test that?

Perhaps that's fixable

**Comment by AbelHo** [comment]
The following is what I did:
```
vid = VideoIO.openvideo("somefile.mp4")
img = read(vid);
VideoIO.framerate(vid)
```
3 out of 5 video still gives:
```1//0```

2 out of 5 video successfully give the frame rate after reading one frame

**Comment by IanButterworth** [comment]
Can you try https://github.com/JuliaIO/VideoIO.jl/pull/393

**Comment by AbelHo** [comment]
Results from the current master branch before:
```
julia> VideoIO.framerate.(VideoIO.openvideo.(fnames))
5-element Vector{Rational{Int32}}:
 1//0
 1//0
 1//0
 1//0
 1//0

julia> map(fnames) do x
               vid=VideoIO.openvideo(x); read(vid); VideoIO.framerate(vid)
       end
5-element Vector{Rational{Int32}}:
    1//0
   50//1
 3840//1
    1//0
    1//0

julia> get_fps.(fnames)
5-element Vector{Rational{Int64}}:
 30//1
 25//1
 30//1
 25//1
 25//1
```

**Comment by AbelHo** [comment]
> Can you try #393

Thank you.
tested, added results for both before and after changes, here and in #393 respectively

**Comment by IanButterworth** [comment]
@AbelHo thanks for the help here. I'm going to close this and try to finish all the framerate fixes over in #393 

I'd appreciate your review there as I can't see why tests are failing currently

**Pull request closed without merging**
