### PR TITLE
Add AVDictionary wrapper, set default framerate for video capture

### PR DESCRIPTION
**Pull request by kmsquire**
Add DEFAULT_CAMERA_OPTIONS

* Some cameras (particularly built-in webcams) can't handle the
  default framerate of 29.97 FPS.  This commit sets the default to
  30FPS, and on OSX, sets the default `pixel_format` to `uyvy422`
* These options should probably not be hard coded, but instead
  should be set by the user and stored somewhere.  But for now,
  this gets the camera closer to working on OSX.

### CODE REVIEW

**Comment by ianshmean** [comment]
I just tried this out on my 2018 mac and it works. Although, the `ImageView` method for displaying the images is failing:

```julia
julia> camera = opencamera()
VideoReader(...)
julia> using ImageView

julia> play(camera,true)
ERROR: MethodError: no method matching imshow(::Pair{String,Any}, ::PermutedDimsArray{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2,(2, 1),(2, 1),Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2}}; flipx=true, interactive=false)
Closest candidates are:
  imshow(::GtkReactive.Canvas, ::AbstractArray{T,2} where T) at /Users/ian/.julia/packages/ImageView/bEIAo/src/ImageView.jl:184 got unsupported keyword arguments "flipx", "interactive"
  imshow(::GtkReactive.Canvas, ::AbstractArray{T,2} where T, ::Any; kwargs...) at /Users/ian/.julia/packages/ImageView/bEIAo/src/ImageView.jl:184
  imshow(::AbstractArray, ::Any; axes, name, aspect) at /Users/ian/.julia/packages/ImageView/bEIAo/src/ImageView.jl:190 got unsupported keyword arguments "flipx", "interactive"
  ...
Stacktrace:
 [1] play(::VideoIO.VideoReader{true}, ::Bool) at /Users/ian/.julia/packages/VideoIO/J71th/src/VideoIO.jl:88
 [2] top-level scope at none:0
```

Also, even though I get that far, the convenience function `viewcam()` isn't available for me:
```julia
julia> VideoIO.viewcam()
ERROR: UndefVarError: viewcam not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./sysimg.jl:13
 [2] top-level scope at none:0
```

**Comment by ianshmean** [comment]
Apologies @kmsquire I just realized that the errors I saw above were due to importing `ImageView` after `VideoIO`. However, I'm having `Gtk` issues with `ImageView`. Does the play method work for you?

**Comment by kmsquire** [comment]
Last I checked, I had almost gotten it working on my mac, but I had an issue installing ImageView.  This was back in March (when I made this PR), so I'll try again tomorrow.

**Comment by ianshmean** [comment]
Yeah, I've been struggling with installing `ImageView` too. I was having unsatisfiable requirements issues with `GtkReactive` which _seem_ to have been fixed by just moving `GtkReactive` to `Project.toml`, which I did here: https://github.com/JuliaGizmos/GtkReactive.jl/pull/85 (Maybe it's a coincidence, because I can't figure out why..)

Now I get:
```julia
julia> VideoIO.viewcam()
FATAL ERROR: Gtk state corrupted by error thrown in a callback:
ERROR: AssertionError: g_stack === nothing && !prev
Stacktrace:
 [1] g_sigatom(::Any) at /Users/ian/.julia/packages/Gtk/aP55V/src/GLib/signals.jl:165
 [2] macro expansion at /Users/ian/.julia/packages/Gtk/aP55V/src/GLib/signals.jl:191 [inlined]
 [3] show at /Users/ian/.julia/packages/Gtk/aP55V/src/base.jl:35 [inlined]
 [4] Gtk.GtkWindowLeaf(::String, ::Int64, ::Int64, ::Bool, ::Bool) at /Users/ian/.julia/packages/Gtk/aP55V/src/windows.jl:14
 [5] Type at /Users/ian/.julia/packages/Gtk/aP55V/src/windows.jl:2 [inlined]
 [6] #GtkWindow#188 at /Users/ian/.julia/packages/Gtk/aP55V/src/GLib/gtype.jl:226 [inlined]
 [7] Type at /Users/ian/.julia/packages/Gtk/aP55V/src/GLib/gtype.jl:226 [inlined]
 [8] #imshow_gui#26(::String, ::Symbol, ::Function, ::Tuple{Int64,Int64}, ::ImageView.SliceData{false,0,Tuple{}}, ::Tuple{Int64,Int64}) at /Users/ian/.julia/packages/ImageView/1uiRS/src/ImageView.jl:295
 [9] #imshow_gui at ./none:0 [inlined] (repeats 2 times)
 [10] #imshow#17(::String, ::Symbol, ::Function, ::SubArray{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2,MappedArrays.ReadonlyMappedArray{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2,PermutedDimsArray{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2,(2, 1),(2, 1),Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2}},typeof(identity)},Tuple{Base.OneTo{Int64},StepRange{Int64,Int64}},false}, ::Reactive.Signal{CLim{ColorTypes.RGB{Float64}}}, ::Reactive.Signal{GtkReactive.ZoomRegion{RoundingIntegers.RInt64}}, ::ImageView.SliceData{false,0,Tuple{}}, ::Reactive.Signal{Dict{UInt64,Any}}) at /Users/ian/.julia/packages/ImageView/1uiRS/src/ImageView.jl:200
 [11] #imshow at ./none:0 [inlined] (repeats 2 times)
 [12] #imshow#13(::Tuple{Int64,Int64}, ::String, ::Function, ::Symbol, ::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol,Symbol},NamedTuple{(:flipx, :interactive),Tuple{Bool,Bool}}}, ::Function, ::PermutedDimsArray{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2,(2, 1),(2, 1),Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2}}) at /Users/ian/.julia/packages/ImageView/1uiRS/src/ImageView.jl:177
 [13] (::getfield(ImageView, Symbol("#kw##imshow")))(::NamedTuple{(:flipx, :interactive),Tuple{Bool,Bool}}, ::typeof(imshow), ::PermutedDimsArray{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2,(2, 1),(2, 1),Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2}}) at ./none:0
 [14] play(::VideoIO.VideoReader{true}, ::Bool) at /Users/ian/Documents/GitHub/VideoIO.jl/src/VideoIO.jl:84
 [15] viewcam(::String, ::Ptr{VideoIO.AVFormat.AVInputFormat}) at /Users/ian/Documents/GitHub/VideoIO.jl/src/VideoIO.jl:101
 [16] viewcam() at /Users/ian/Documents/GitHub/VideoIO.jl/src/VideoIO.jl:100
 [17] top-level scope at none:0

ERROR: AssertionError: g_stack === nothing && !prev
Stacktrace:
 [1] g_sigatom(::Any) at /Users/ian/.julia/packages/Gtk/aP55V/src/GLib/signals.jl:165
 [2] macro expansion at /Users/ian/.julia/packages/Gtk/aP55V/src/GLib/signals.jl:191 [inlined]
 [3] show at /Users/ian/.julia/packages/Gtk/aP55V/src/base.jl:35 [inlined]
 [4] Gtk.GtkWindowLeaf(::String, ::Int64, ::Int64, ::Bool, ::Bool) at /Users/ian/.julia/packages/Gtk/aP55V/src/windows.jl:14
 [5] Type at /Users/ian/.julia/packages/Gtk/aP55V/src/windows.jl:2 [inlined]
 [6] #GtkWindow#188 at /Users/ian/.julia/packages/Gtk/aP55V/src/GLib/gtype.jl:226 [inlined]
 [7] Type at /Users/ian/.julia/packages/Gtk/aP55V/src/GLib/gtype.jl:226 [inlined]
 [8] #imshow_gui#26(::String, ::Symbol, ::Function, ::Tuple{Int64,Int64}, ::ImageView.SliceData{false,0,Tuple{}}, ::Tuple{Int64,Int64}) at /Users/ian/.julia/packages/ImageView/1uiRS/src/ImageView.jl:295
 [9] #imshow_gui at ./none:0 [inlined] (repeats 2 times)
 [10] #imshow#17(::String, ::Symbol, ::Function, ::SubArray{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2,MappedArrays.ReadonlyMappedArray{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2,PermutedDimsArray{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2,(2, 1),(2, 1),Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2}},typeof(identity)},Tuple{Base.OneTo{Int64},StepRange{Int64,Int64}},false}, ::Reactive.Signal{CLim{ColorTypes.RGB{Float64}}}, ::Reactive.Signal{GtkReactive.ZoomRegion{RoundingIntegers.RInt64}}, ::ImageView.SliceData{false,0,Tuple{}}, ::Reactive.Signal{Dict{UInt64,Any}}) at /Users/ian/.julia/packages/ImageView/1uiRS/src/ImageView.jl:200
 [11] #imshow at ./none:0 [inlined] (repeats 2 times)
 [12] #imshow#13(::Tuple{Int64,Int64}, ::String, ::Function, ::Symbol, ::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol,Symbol},NamedTuple{(:flipx, :interactive),Tuple{Bool,Bool}}}, ::Function, ::PermutedDimsArray{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2,(2, 1),(2, 1),Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2}}) at /Users/ian/.julia/packages/ImageView/1uiRS/src/ImageView.jl:177
 [13] (::getfield(ImageView, Symbol("#kw##imshow")))(::NamedTuple{(:flipx, :interactive),Tuple{Bool,Bool}}, ::typeof(imshow), ::PermutedDimsArray{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2,(2, 1),(2, 1),Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2}}) at ./none:0
 [14] play(::VideoIO.VideoReader{true}, ::Bool) at /Users/ian/Documents/GitHub/VideoIO.jl/src/VideoIO.jl:84
 [15] viewcam(::String, ::Ptr{VideoIO.AVFormat.AVInputFormat}) at /Users/ian/Documents/GitHub/VideoIO.jl/src/VideoIO.jl:101
 [16] viewcam() at /Users/ian/Documents/GitHub/VideoIO.jl/src/VideoIO.jl:100
 [17] top-level scope at none:0
```

**Comment by ianshmean** [comment]
@kmsquire I've replaced the ImageView video view method with a Makie method. 
I can view videos but I'm still getting camera load errors on this branch for `VideoIO.viewcam()`

**Comment by ianshmean** [comment]
Webcam playback via Makie now works via this PR on my Macbook. It would be good to test this on multiple machines/platforms. cc @schlichtanders @hearnsj @kmsquire ?

```julia
using Makie, VideoIO
VideoIO.viewcam()
```

However, there's a segfault in testing that occurs after 2 videos on MacOS, and after 3 videos on Linux. I've not managed to figure out out yet

**Comment by hearnsj** [comment]
On Windows 10..   crash and burn.
Though the file is there, so there is something wrong at my end.

v1.1) pkg> add VideoIO#kms/avdictionary_framerate
  Updating git-repo `https://github.com/JuliaIO/VideoIO.jl.git`
 Resolving package versions...
  Updating `C:\Users\hearn\.julia\environments\v1.1\Project.toml`
  [d6d074c3] + VideoIO v0.6.0 #kms/avdictionary_framerate (https://github.com/JuliaIO/VideoIO.jl.git)
  Updating `C:\Users\hearn\.julia\environments\v1.1\Manifest.toml`
  [d6d074c3] + VideoIO v0.6.0 #kms/avdictionary_framerate (https://github.com/JuliaIO/VideoIO.jl.git)
  Building VideoIO → `C:\Users\hearn\.julia\packages\VideoIO\Gi9NE\deps\build.log`
┌ Error: Error building `VideoIO`:
│ ┌ Warning: Could not extract the platform key of https://github.com/ianshmean/FFMPEG-tarballs/raw/master/4.1/bin/ffmpeg-4.1-win64-shared.tar.gz; continuing...
│ └ @ BinaryProvider C:\Users\hearn\.julia\packages\BinaryProvider\TcAwt\src\Prefix.jl:185
│ [ Info: Downloading https://github.com/ianshmean/FFMPEG-tarballs/raw/master/4.1/bin/ffmpeg-4.1-win64-shared.tar.gz to C:\Users\hearn\.julia\packages\VideoIO\Gi9NE\deps\usr\downloads\ffmpeg-4.1-win64-shared.tar.gz...
│ ERROR: LoadError: Could not download https://github.com/ianshmean/FFMPEG-tarballs/raw/master/4.1/bin/ffmpeg-4.1-win64-shared.tar.gz to C:\Users\hearn\.julia\packages\VideoIO\Gi9NE\deps\usr\downloads\ffmpeg-4.1-win64-shared.tar.gz:

**Comment by ianshmean** [comment]
@hearnsj Tip.. If you wrap code in triple backticks, it's a lot easier to read on issues: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

Your issue seems to be with the BinaryProvider move. It looks like your download target folder is malformed.. `C:\Users\hearn.julia\...` Are you able to install v0.6.0?

**Comment by hearnsj** [comment]
It works now.. sorry. Must have been a glitch.

**Comment by hearnsj** [comment]
Windows 10

julia> VideoIO.viewcam()
ERROR: UndefVarError: viewcam not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at .\sysimg.jl:13
 [2] top-level scope at none:0

**Comment by ianshmean** [comment]
Are you importing Makie first? If not, you'll need to start a new julia session and do:
```
using Makie, VideoIO
VideoIO.viewcam()
```

**Comment by ianshmean** [comment]
I added a helper functions to serve errors in case 1) no AV device is detected and 2) `Makie` isn't loaded before `VideoIO`

**Comment by ianshmean** [comment]
Closed as #163 merged

**Pull request closed without merging**
