### PR TITLE
update sample code to latest Makie API fix #354

### LINKED ISSUE #354: "Video Playback" code is not working with latest Makie
The [sample code for "Video Playback"](https://juliaio.github.io/VideoIO.jl/stable/reading/#Video-Playback) has deprecated and no-longer-supported code.

Specifically, `show_axis` and `scale_plot` have been deprecated

### PR DESCRIPTION
**Pull request by FelipeLema**
`show_axis` & `scale_plot` no longer supported

fixes #354

### CODE REVIEW

**Comment by IanButterworth** [comment]
@FelipeLema I hope you don't mind, I pushed some more fixes for the docs and `viewcam`.

Would you mind testing whether `viewcam()` works for you? On MacOS for me it loads and grabs images but nothing shows in the Makie window.

**Comment by FelipeLema** [comment]
it shows a blank screen to me too. Let me have a go at it

**Comment by FelipeLema** [comment]
It properly shows a x-flipped image from my webcam (mimics a mirror)

there are some other details (provided width & height is ignored), but I guess we can go with this one in the meantime

shoutouts to macOS' GateKeeper for quietly blocking me on this one for so long

**Comment by FelipeLema** [comment]
I dunno what's up with format linter, but this is ready to go

**Comment by IanButterworth** [comment]
Thanks I'll test locally and fix the formatter (this is the first PR after I added that, so it's good to fix it)

**Pull request merged**
