### PR TITLE
Add OSX (travis) and Windows (appveyor) testing

### PR DESCRIPTION
**Pull request by kmsquire**

### CODE REVIEW

**Comment by ianshmean** [comment]
@kmsquire Can this be closed given your latest PR?

**Comment by kmsquire** [comment]
Well, that PR isn't working without your fixes. 🙂 Let's close it after meeting your PR.

**Comment by ianshmean** [comment]
Closing as covered by #138

**Comment by kmsquire** [comment]
I just realized that we don't actually test on OSX with travis. I actually think I might have disabled it because of how slow it usually is. But now that Appveyor is enabled, maybe it won't seem so slow. 😊

**Comment by ianshmean** [comment]
I should've realized! It didn't occur to me that travis was so much quicker than my local builds on osx! 
I've created https://github.com/JuliaIO/VideoIO.jl/pull/142

**Pull request closed without merging**
